import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Common/Header";
import Footer from "./Common/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MainContext from "./Context/MainContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainContext>
          <Header />
          {children}
          <Footer />
          <ToastContainer />
        </MainContext>

      </body>
    </html>
  );
}
